In [1]:
import os
os.getcwd()

# Make sure server_pull.py file is in the same working directory

'/Users/matthieuzekhout/Documents/6. Academics/3. NUS - MSBA/3. Courses/2. DBA5101 - Analytics in Managerial Economics/Group Assignment 3'

In [2]:
# Make sure you are connected to NUS wifi or NUS VPN in order to import and run this function
# see the link below
# https://webvpn.nus.edu.sg/dana-na/auth/url_52/welcome.cgi

# Use server_pull_updated
#from server_pull_updated import pull
from server_pull import pull

# pull function has the following syntax: pull(user_group, secret_key, arm)
# please change 'test_user' and 'aaaaaaaa' to your own user_group and secret_key respectively

output = pull('test_user','aaaaaaaa',19)
#output = pull('user32','cnERvnBr',2)
output

# output comes as a dictionary with 4 key-value pairs; 
# Arm you pulled, Net Reward so far, How many times you have pulled, and reward from current pull

{'Arm': '19', 'NetReward': 7336492, 'Pull': 344477, 'Reward': 8}

In [3]:
# Each value can be accessed like a normal dictionary
output['Arm']

'19'

In [4]:
output['Reward']

8

In [5]:
output

{'Arm': '19', 'NetReward': 7336492, 'Pull': 344477, 'Reward': 8}

In [6]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt

NetReward = 0
NetPull = 0
number_machine = 24

In [7]:
def pull(user_group, secret_key, machine_num):
    global NetReward
    global NetPull
    NetReward = NetReward + 1
    NetPull = NetPull + 1
    return {'Arm': str(machine_num), 'NetReward': NetReward, 'Pull' : NetPull, 'Reward':  np.random.randint(0, 100)}

In [8]:
def epsilon_greedy (user_group, password, tot_rounds, number_machine, epsilon):    
    
    result = {idx + 1: {
        "Arm": idx + 1,
        "Output_Arm": 0,
        "Pulls": 0,
        "Reward_List": [],
        "Total_Reward": 0,
        "Average_Reward": 0
        } for idx in range(number_machine) }
    
    for num_round in range(1, tot_rounds + 1):        
        if random.random() < epsilon or num_round == 1:
            arm = random.randint(1, number_machine)
            print(f"# {num_round}, Exploring Arm {arm}...")
        else:
            arm = max(result, key=lambda k: sum(result[k]["Reward_List"]) / result[k]["Pulls"] if result[k]["Pulls"] > 0 else 0)
            print(f"# {num_round}, Exploiting Arm {arm}...")
            
        output = pull(user_group, password, arm)
        
        result[arm]["Output_Arm"] = output["Arm"]
        result[arm]["Reward_List"].append(output["Reward"])
        result[arm]["Pulls"] += 1
        result[arm]["Total_Reward"] = sum(result[arm]["Reward_List"])
        result[arm]["Average_Reward"] = 0 if result[arm]["Pulls"] == 0 else result[arm]["Total_Reward"]/result[arm]["Pulls"]
        
    return result

In [9]:
result = epsilon_greedy("test_user","aaaaaaaa", 300, 24, 0.4)
if result:
    print("\nResults")
    for key in result.keys():
        print(result[key])

# 1, Exploring Arm 20...
# 2, Exploring Arm 10...
# 3, Exploring Arm 24...
# 4, Exploiting Arm 10...
# 5, Exploiting Arm 10...
# 6, Exploring Arm 22...
# 7, Exploiting Arm 22...
# 8, Exploiting Arm 10...
# 9, Exploiting Arm 22...
# 10, Exploiting Arm 10...
# 11, Exploiting Arm 10...
# 12, Exploiting Arm 22...
# 13, Exploring Arm 18...
# 14, Exploring Arm 18...
# 15, Exploiting Arm 10...
# 16, Exploiting Arm 10...
# 17, Exploring Arm 15...
# 18, Exploiting Arm 15...
# 19, Exploiting Arm 10...
# 20, Exploiting Arm 10...
# 21, Exploiting Arm 10...
# 22, Exploring Arm 2...
# 23, Exploiting Arm 15...
# 24, Exploiting Arm 22...
# 25, Exploiting Arm 10...
# 26, Exploiting Arm 24...
# 27, Exploiting Arm 24...
# 28, Exploiting Arm 24...
# 29, Exploiting Arm 10...
# 30, Exploiting Arm 15...
# 31, Exploring Arm 22...
# 32, Exploiting Arm 10...
# 33, Exploiting Arm 22...
# 34, Exploring Arm 21...
# 35, Exploiting Arm 10...
# 36, Exploring Arm 16...
# 37, Exploiting Arm 10...
# 38, Exploiting Arm 10...
# 39, Exploring Arm 13...
# 40, Exploiting Arm 13...
# 41, Exploiting Arm 13...
# 42, Exploring Arm 14...
# 43, Exploring Arm 11...
# 44, Exploring Arm 12...
# 45, Exploiting Arm 11...
# 46, Exploiting Arm 13...
# 47, Exploiting Arm 14...
# 48, Exploring Arm 4...
# 49, Exploiting Arm 13...
# 50, Exploiting Arm 13...
# 51, Exploring Arm 19...
# 52, Exploring Arm 7...
# 53, Exploiting Arm 13...
# 54, Exploiting Arm 13...
# 55, Exploring Arm 18...
# 56, Exploiting Arm 13...
# 57, Exploring Arm 12...
# 58, Exploiting Arm 13...
# 59, Exploiting Arm 13...
# 60, Exploring Arm 20...
# 61, Exploring Arm 12...
# 62, Exploiting Arm 13...
# 63, Exploiting Arm 13...
# 64, Exploring Arm 5...
# 65, Exploiting Arm 13...
# 66, Exploring Arm 15...
# 67, Exploiting Arm 13...
# 68, Exploring Arm 18...
# 69, Exploring Arm 9...
# 70, Exploring Arm 17...
# 71, Exploiting Arm 13...
# 72, Exploiting Arm 13...
# 73, Exploiting Arm 13...
# 74, Exploiting Arm 13...
# 75, Exploring Arm 8...
# 76, Exploring Arm 4...
# 77, Exploiting Arm 11...
# 78, Exploring Arm 6...
# 79, Exploiting Arm 6...
# 80, Exploiting Arm 6...
# 81, Exploring Arm 3...
# 82, Exploring Arm 2...
# 83, Exploiting Arm 6...
# 84, Exploiting Arm 3...
# 85, Exploiting Arm 3...
# 86, Exploiting Arm 3...
# 87, Exploiting Arm 6...
# 88, Exploiting Arm 3...
# 89, Exploiting Arm 13...
# 90, Exploring Arm 24...
# 91, Exploiting Arm 13...
# 92, Exploiting Arm 13...
# 93, Exploring Arm 8...
# 94, Exploring Arm 1...
# 95, Exploring Arm 1...
# 96, Exploiting Arm 10...
# 97, Exploiting Arm 13...
# 98, Exploiting Arm 13...
# 99, Exploiting Arm 3...
# 100, Exploring Arm 18...
# 101, Exploiting Arm 3...
# 102, Exploiting Arm 3...
# 103, Exploiting Arm 15...
# 104, Exploring Arm 15...
# 105, Exploiting Arm 15...
# 106, Exploiting Arm 21...
# 107, Exploring Arm 2...
# 108, Exploiting Arm 21...
# 109, Exploring Arm 12...
# 110, Exploiting Arm 15...
# 111, Exploiting Arm 13...
# 112, Exploiting Arm 13...
# 113, Exploiting Arm 13...
# 114, Exploring Arm 1...
# 115, Exploiting Arm 10...
# 116, Exploring Arm 14...
# 117, Exploiting Arm 13...
# 118, Exploiting Arm 12...
# 119, Exploring Arm 19...
# 120, Exploring Arm 17...
# 121, Exploiting Arm 17...
# 122, Exploiting Arm 17...
# 123, Exploring Arm 3...
# 124, Exploiting Arm 17...
# 125, Exploiting Arm 17...
# 126, Exploiting Arm 17...
# 127, Exploring Arm 17...
# 128, Exploiting Arm 17...
# 129, Exploiting Arm 17...
# 130, Exploring Arm 7...
# 131, Exploring Arm 18...
# 132, Exploring Arm 13...
# 133, Exploring Arm 7...
# 134, Exploiting Arm 7...
# 135, Exploiting Arm 17...
# 136, Exploiting Arm 17...
# 137, Exploiting Arm 7...
# 138, Exploiting Arm 12...
# 139, Exploiting Arm 12...
# 140, Exploiting Arm 7...
# 141, Exploiting Arm 7...
# 142, Exploring Arm 3...
# 143, Exploring Arm 5...
# 144, Exploiting Arm 7...
# 145, Exploiting Arm 7...
# 146, Exploiting Arm 7...
# 147, Exploiting Arm 7...
# 148, Exploiting Arm 7...
# 149, Exploring Arm 12...
# 150, Exploiting Arm 7...
# 151, Exploiting Arm 7...
# 152, Exploiting Arm 7...
# 153, Exploiting Arm 7...
# 154, Exploring Arm 13...
# 155, Exploiting Arm 7...
# 156, Exploiting Arm 7...
# 157, Exploiting Arm 7...
# 158, Exploring Arm 21...
# 159, Exploiting Arm 7...
# 160, Exploiting Arm 7...
# 161, Exploring Arm 17...
# 162, Exploiting Arm 17...
# 163, Exploring Arm 22...
# 164, Exploring Arm 15...
# 165, Exploring Arm 16...
# 166, Exploring Arm 19...
# 167, Exploiting Arm 17...
# 168, Exploiting Arm 17...
# 169, Exploiting Arm 17...
# 170, Exploring Arm 4...
# 171, Exploiting Arm 4...
# 172, Exploiting Arm 17...
# 173, Exploring Arm 11...
# 174, Exploring Arm 22...
# 175, Exploiting Arm 7...
# 176, Exploiting Arm 7...
# 177, Exploring Arm 8...
# 178, Exploring Arm 2...
# 179, Exploring Arm 10...
# 180, Exploring Arm 17...
# 181, Exploiting Arm 12...
# 182, Exploiting Arm 7...
# 183, Exploiting Arm 4...
# 184, Exploring Arm 14...
# 185, Exploring Arm 16...
# 186, Exploiting Arm 4...
# 187, Exploiting Arm 4...
# 188, Exploring Arm 5...
# 189, Exploiting Arm 17...
# 190, Exploiting Arm 17...
# 191, Exploring Arm 11...
# 192, Exploiting Arm 17...
# 193, Exploring Arm 9...
# 194, Exploiting Arm 9...
# 195, Exploring Arm 18...
# 196, Exploiting Arm 9...
# 197, Exploring Arm 24...
# 198, Exploring Arm 17...
# 199, Exploiting Arm 9...
# 200, Exploring Arm 14...
# 201, Exploiting Arm 9...
# 202, Exploiting Arm 13...
# 203, Exploring Arm 10...
# 204, Exploring Arm 22...
# 205, Exploring Arm 24...
# 206, Exploiting Arm 22...
# 207, Exploiting Arm 13...
# 208, Exploiting Arm 13...
# 209, Exploiting Arm 13...
# 210, Exploring Arm 16...
# 211, Exploring Arm 21...
# 212, Exploring Arm 20...
# 213, Exploiting Arm 13...
# 214, Exploiting Arm 13...
# 215, Exploring Arm 20...
# 216, Exploiting Arm 13...
# 217, Exploring Arm 20...
# 218, Exploring Arm 3...
# 219, Exploring Arm 13...
# 220, Exploiting Arm 7...
# 221, Exploiting Arm 7...
# 222, Exploiting Arm 7...
# 223, Exploiting Arm 7...
# 224, Exploiting Arm 7...
# 225, Exploiting Arm 7...
# 226, Exploiting Arm 7...
# 227, Exploiting Arm 7...
# 228, Exploring Arm 16...
# 229, Exploiting Arm 7...
# 230, Exploiting Arm 7...
# 231, Exploiting Arm 7...
# 232, Exploiting Arm 7...
# 233, Exploiting Arm 7...
# 234, Exploring Arm 12...
# 235, Exploring Arm 6...
# 236, Exploring Arm 6...
# 237, Exploiting Arm 6...
# 238, Exploiting Arm 6...
# 239, Exploring Arm 6...
# 240, Exploring Arm 15...
# 241, Exploiting Arm 6...
# 242, Exploring Arm 17...
# 243, Exploiting Arm 7...
# 244, Exploiting Arm 7...
# 245, Exploring Arm 11...
# 246, Exploring Arm 8...
# 247, Exploiting Arm 7...
# 248, Exploiting Arm 7...
# 249, Exploiting Arm 7...
# 250, Exploiting Arm 7...
# 251, Exploring Arm 8...
# 252, Exploiting Arm 7...
# 253, Exploring Arm 13...
# 254, Exploring Arm 22...
# 255, Exploring Arm 20...
# 256, Exploring Arm 18...
# 257, Exploiting Arm 7...
# 258, Exploiting Arm 7...
# 259, Exploiting Arm 7...
# 260, Exploiting Arm 7...
# 261, Exploring Arm 23...
# 262, Exploring Arm 3...
# 263, Exploiting Arm 7...
# 264, Exploring Arm 1...
# 265, Exploring Arm 18...
# 266, Exploiting Arm 7...
# 267, Exploring Arm 4...
# 268, Exploring Arm 24...
# 269, Exploiting Arm 7...
# 270, Exploiting Arm 7...
# 271, Exploring Arm 24...
# 272, Exploring Arm 11...
# 273, Exploiting Arm 7...
# 274, Exploiting Arm 7...
# 275, Exploring Arm 20...
# 276, Exploring Arm 19...
# 277, Exploring Arm 16...
# 278, Exploiting Arm 7...
# 279, Exploring Arm 24...
# 280, Exploring Arm 4...
# 281, Exploring Arm 8...
# 282, Exploiting Arm 7...
# 283, Exploring Arm 7...
# 284, Exploiting Arm 7...
# 285, Exploiting Arm 7...
# 286, Exploiting Arm 7...
# 287, Exploiting Arm 7...
# 288, Exploring Arm 13...
# 289, Exploring Arm 12...
# 290, Exploiting Arm 7...
# 291, Exploiting Arm 7...
# 292, Exploiting Arm 7...
# 293, Exploiting Arm 7...
# 294, Exploiting Arm 6...
# 295, Exploiting Arm 6...
# 296, Exploiting Arm 4...
# 297, Exploiting Arm 4...
# 298, Exploring Arm 3...
# 299, Exploiting Arm 4...
# 300, Exploiting Arm 4...

Results
{'Arm': 1, 'Output_Arm': '1', 'Pulls': 4, 'Reward_List': [12, 27, 2, 36], 'Total_Reward': 77, 'Average_Reward': 19.25}
{'Arm': 2, 'Output_Arm': '2', 'Pulls': 4, 'Reward_List': [48, 19, 38, 21], 'Total_Reward': 126, 'Average_Reward': 31.5}
{'Arm': 3, 'Output_Arm': '3', 'Pulls': 13, 'Reward_List': [59, 94, 72, 0, 40, 97, 21, 27, 25, 78, 25, 94, 57], 'Total_Reward': 689, 'Average_Reward': 53.0}
{'Arm': 4, 'Output_Arm': '4', 'Pulls': 13, 'Reward_List': [50, 52, 86, 29, 92, 24, 13, 49, 91, 73, 67, 88, 86], 'Total_Reward': 800, 'Average_Reward': 61.53846153846154}
{'Arm': 5, 'Output_Arm': '5', 'Pulls': 3, 'Reward_List': [2, 35, 72], 'Total_Reward': 109, 'Average_Reward': 36.333333333333336}
{'Arm': 6, 'Output_Arm': '6', 'Pulls': 13, 'Reward_List': [96, 65, 51, 18, 12, 88, 83, 87, 27, 52, 16, 58, 8], 'Total_Reward': 661, 'Average_Reward': 50.84615384615385}
{'Arm': 7, 'Output_Arm': '7', 'Pulls': 65, 'Reward_List': [34, 70, 82, 39, 49, 91, 99, 90, 4, 46, 84, 89, 69, 56, 46, 21, 32, 87, 62, 35, 5, 51, 12, 11, 65, 54, 71, 95, 41, 7, 50, 85, 93, 40, 53, 67, 75, 40, 99, 36, 79, 98, 36, 68, 47, 97, 35, 53, 82, 55, 17, 44, 92, 62, 3, 43, 29, 65, 92, 29, 44, 21, 5, 42, 0], 'Total_Reward': 3473, 'Average_Reward': 53.43076923076923}
{'Arm': 8, 'Output_Arm': '8', 'Pulls': 6, 'Reward_List': [0, 85, 34, 56, 8, 35], 'Total_Reward': 218, 'Average_Reward': 36.333333333333336}
{'Arm': 9, 'Output_Arm': '9', 'Pulls': 6, 'Reward_List': [15, 97, 63, 68, 24, 12], 'Total_Reward': 279, 'Average_Reward': 46.5}
{'Arm': 10, 'Output_Arm': '10', 'Pulls': 21, 'Reward_List': [99, 65, 83, 37, 42, 50, 94, 7, 55, 99, 13, 48, 38, 17, 63, 81, 30, 23, 23, 83, 10], 'Total_Reward': 1060, 'Average_Reward': 50.476190476190474}
{'Arm': 11, 'Output_Arm': '11', 'Pulls': 7, 'Reward_List': [96, 16, 7, 9, 28, 18, 92], 'Total_Reward': 266, 'Average_Reward': 38.0}
{'Arm': 12, 'Output_Arm': '12', 'Pulls': 11, 'Reward_List': [34, 80, 18, 77, 68, 74, 24, 66, 21, 48, 60], 'Total_Reward': 570, 'Average_Reward': 51.81818181818182}
{'Arm': 13, 'Output_Arm': '13', 'Pulls': 40, 'Reward_List': [87, 75, 43, 36, 92, 43, 68, 92, 25, 88, 80, 56, 30, 28, 61, 86, 12, 21, 41, 69, 10, 39, 43, 35, 73, 59, 23, 18, 50, 99, 65, 89, 68, 63, 53, 21, 21, 31, 88, 0], 'Total_Reward': 2081, 'Average_Reward': 52.025}
{'Arm': 14, 'Output_Arm': '14', 'Pulls': 5, 'Reward_List': [64, 31, 8, 69, 54], 'Total_Reward': 226, 'Average_Reward': 45.2}
{'Arm': 15, 'Output_Arm': '15', 'Pulls': 11, 'Reward_List': [96, 22, 54, 13, 80, 76, 31, 49, 20, 53, 78], 'Total_Reward': 572, 'Average_Reward': 52.0}
{'Arm': 16, 'Output_Arm': '16', 'Pulls': 6, 'Reward_List': [19, 49, 59, 71, 39, 77], 'Total_Reward': 314, 'Average_Reward': 52.333333333333336}
{'Arm': 17, 'Output_Arm': '17', 'Pulls': 24, 'Reward_List': [38, 74, 84, 89, 71, 5, 75, 60, 64, 33, 53, 6, 97, 78, 60, 44, 50, 15, 23, 81, 43, 14, 38, 39], 'Total_Reward': 1234, 'Average_Reward': 51.416666666666664}
{'Arm': 18, 'Output_Arm': '18', 'Pulls': 9, 'Reward_List': [19, 21, 53, 83, 78, 3, 22, 52, 82], 'Total_Reward': 413, 'Average_Reward': 45.888888888888886}
{'Arm': 19, 'Output_Arm': '19', 'Pulls': 4, 'Reward_List': [10, 10, 34, 13], 'Total_Reward': 67, 'Average_Reward': 16.75}
{'Arm': 20, 'Output_Arm': '20', 'Pulls': 7, 'Reward_List': [35, 64, 20, 56, 64, 70, 39], 'Total_Reward': 348, 'Average_Reward': 49.714285714285715}
{'Arm': 21, 'Output_Arm': '21', 'Pulls': 5, 'Reward_List': [53, 99, 1, 40, 42], 'Total_Reward': 235, 'Average_Reward': 47.0}
{'Arm': 22, 'Output_Arm': '22', 'Pulls': 12, 'Reward_List': [97, 48, 44, 47, 37, 48, 28, 83, 40, 70, 3, 59], 'Total_Reward': 604, 'Average_Reward': 50.333333333333336}
{'Arm': 23, 'Output_Arm': '23', 'Pulls': 1, 'Reward_List': [36], 'Total_Reward': 36, 'Average_Reward': 36.0}
{'Arm': 24, 'Output_Arm': '24', 'Pulls': 10, 'Reward_List': [58, 91, 51, 2, 55, 4, 13, 65, 0, 21], 'Total_Reward': 360, 'Average_Reward': 36.0}

In [10]:
df = pd.DataFrame(result.values())
df

,Arm,Output_Arm,Pulls,Reward_List,Total_Reward,Average_Reward
0,1,1,4,"[12, 27, 2, 36]",77,19.250000
1,2,2,4,"[48, 19, 38, 21]",126,31.500000
2,3,3,13,"[59, 94, 72, 0, 40, 97, 21, 27, 25, 78, 25, 94...",689,53.000000
3,4,4,13,"[50, 52, 86, 29, 92, 24, 13, 49, 91, 73, 67, 8...",800,61.538462
4,5,5,3,"[2, 35, 72]",109,36.333333
5,6,6,13,"[96, 65, 51, 18, 12, 88, 83, 87, 27, 52, 16, 5...",661,50.846154
6,7,7,65,"[34, 70, 82, 39, 49, 91, 99, 90, 4, 46, 84, 89...",3473,53.430769
7,8,8,6,"[0, 85, 34, 56, 8, 35]",218,36.333333
8,9,9,6,"[15, 97, 63, 68, 24, 12]",279,46.500000
9,10,10,21,"[99, 65, 83, 37, 42, 50, 94, 7, 55, 99, 13, 48...",1060,50.476190
10,11,11,7,"[96, 16, 7, 9, 28, 18, 92]",266,38.000000
11,12,12,11,"[34, 80, 18, 77, 68, 74, 24, 66, 21, 48, 60]",570,51.818182
12,13,13,40,"[87, 75, 43, 36, 92, 43, 68, 92, 25, 88, 80, 5...",2081,52.025000
13,14,14,5,"[64, 31, 8, 69, 54]",226,45.200000
14,15,15,11,"[96, 22, 54, 13, 80, 76, 31, 49, 20, 53, 78]",572,52.000000
15,16,16,6,"[19, 49, 59, 71, 39, 77]",314,52.333333
16,17,17,24,"[38, 74, 84, 89, 71, 5, 75, 60, 64, 33, 53, 6,...",1234,51.416667
17,18,18,9,"[19, 21, 53, 83, 78, 3, 22, 52, 82]",413,45.888889
18,19,19,4,"[10, 10, 34, 13]",67,16.750000
19,20,20,7,"[35, 64, 20, 56, 64, 70, 39]",348,49.714286
20,21,21,5,"[53, 99, 1, 40, 42]",235,47.000000
21,22,22,12,"[97, 48, 44, 47, 37, 48, 28, 83, 40, 70, 3, 59]",604,50.333333
22,23,23,1,[36],36,36.000000
23,24,24,10,"[58, 91, 51, 2, 55, 4, 13, 65, 0, 21]",360,36.000000