In [1]:
import os
os.getcwd()

'/Users/matthieuzekhout/Documents/6. Academics/3. NUS - MSBA/3. Courses/2. DBA5101 - Analytics in Managerial Economics/Group Assignment 3'

In [2]:
# Import the usual
from server_pull import pull
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt

In [12]:
# Check pull function
output = pull('user32','cnERvnBr',2)
output

{'Arm': '2', 'NetReward': 4385278, 'Pull': 230440, 'Reward': 12}

In [4]:
# Define epsilon greedy algorithm
def epsilon_greedy(user_group, password, tot_rounds, number_machine, epsilon):
    pull_details = []
    cumulative_reward = 0
    arm_rewards = {i: [] for i in range(1, number_machine + 1)}

    for num_round in range(1, tot_rounds + 1):
        if random.random() <= epsilon or num_round == 1:
            arm = random.randint(1, number_machine)
            print(f"# {num_round}, Exploring Arm {arm}...")
        else:
            avg_rewards = {arm: (sum(rewards) / len(rewards) if rewards else 0) for arm, rewards in arm_rewards.items()}
            arm = max(avg_rewards, key=avg_rewards.get)
            print(f"# {num_round}, Exploiting Arm {arm}...")
        
        output = pull(user_group, password, arm)
        arm_rewards[arm].append(output["Reward"])
        cumulative_reward += output["Reward"]

        pull_details.append({
            "Pull_Number": num_round,
            "Arm_Pulled": arm,
            "Reward": output["Reward"],
            "Cumulative_Reward": cumulative_reward
        })
        
    return pull_details

In [14]:
# Example usage
result = epsilon_greedy('user40', 'XEq6wByD', 100, 24, 0.3)

if result:
    for pull_info in result:
        print(f"Pull Number: {pull_info['Pull_Number']}, Arm Pulled: {pull_info['Arm_Pulled']}, Reward: {pull_info['Reward']}, Cumulative Reward: {pull_info['Cumulative_Reward']}")

# 1, Exploring Arm 23...
# 2, Exploring Arm 22...
# 3, Exploring Arm 11...
# 4, Exploiting Arm 23...
# 5, Exploiting Arm 23...
# 6, Exploring Arm 8...
# 7, Exploiting Arm 23...
# 8, Exploiting Arm 23...
# 9, Exploiting Arm 23...
# 10, Exploring Arm 16...
# 11, Exploring Arm 18...
# 12, Exploiting Arm 23...
# 13, Exploiting Arm 23...
# 14, Exploring Arm 2...
# 15, Exploring Arm 14...
# 16, Exploiting Arm 2...
# 17, Exploiting Arm 2...
# 18, Exploiting Arm 2...
# 19, Exploiting Arm 2...
# 20, Exploiting Arm 2...
# 21, Exploiting Arm 2...
# 22, Exploring Arm 6...
# 23, Exploiting Arm 2...
# 24, Exploiting Arm 2...
# 25, Exploiting Arm 2...
# 26, Exploring Arm 5...
# 27, Exploiting Arm 5...
# 28, Exploiting Arm 2...
# 29, Exploring Arm 8...
# 30, Exploring Arm 17...
# 31, Exploiting Arm 2...
# 32, Exploring Arm 20...
# 33, Exploring Arm 2...
# 34, Exploring Arm 2...
# 35, Exploiting Arm 20...
# 36, Exploiting Arm 2...
# 37, Exploiting Arm 2...
# 38, Exploiting Arm 2...
# 39, Exploring Arm 18...
# 40, Exploiting Arm 2...
# 41, Exploiting Arm 2...
# 42, Exploiting Arm 2...
# 43, Exploring Arm 22...
# 44, Exploiting Arm 2...
# 45, Exploring Arm 5...
# 46, Exploiting Arm 2...
# 47, Exploiting Arm 2...
# 48, Exploring Arm 9...
# 49, Exploiting Arm 2...
# 50, Exploiting Arm 2...
# 51, Exploring Arm 8...
# 52, Exploiting Arm 2...
# 53, Exploiting Arm 2...
# 54, Exploring Arm 1...
# 55, Exploiting Arm 2...
# 56, Exploiting Arm 2...
# 57, Exploring Arm 2...
# 58, Exploring Arm 12...
# 59, Exploiting Arm 2...
# 60, Exploring Arm 17...
# 61, Exploiting Arm 2...
# 62, Exploring Arm 19...
# 63, Exploiting Arm 2...
# 64, Exploiting Arm 2...
# 65, Exploiting Arm 2...
# 66, Exploiting Arm 2...
# 67, Exploiting Arm 2...
# 68, Exploiting Arm 2...
# 69, Exploiting Arm 2...
# 70, Exploiting Arm 2...
# 71, Exploiting Arm 5...
# 72, Exploiting Arm 5...
# 73, Exploiting Arm 2...
# 74, Exploring Arm 13...
# 75, Exploiting Arm 13...
# 76, Exploiting Arm 2...
# 77, Exploiting Arm 2...
# 78, Exploring Arm 6...
# 79, Exploiting Arm 2...
# 80, Exploring Arm 11...
# 81, Exploiting Arm 2...
# 82, Exploiting Arm 2...
# 83, Exploiting Arm 2...
# 84, Exploring Arm 13...
# 85, Exploiting Arm 2...
# 86, Exploiting Arm 2...
# 87, Exploiting Arm 2...
# 88, Exploiting Arm 2...
# 89, Exploring Arm 6...
# 90, Exploiting Arm 2...
# 91, Exploiting Arm 2...
# 92, Exploiting Arm 2...
# 93, Exploiting Arm 2...
# 94, Exploiting Arm 2...
# 95, Exploiting Arm 2...
# 96, Exploiting Arm 2...
# 97, Exploiting Arm 2...
# 98, Exploiting Arm 2...
# 99, Exploiting Arm 2...
# 100, Exploiting Arm 2...
Pull Number: 1, Arm Pulled: 23, Reward: 22, Cumulative Reward: 22
Pull Number: 2, Arm Pulled: 22, Reward: 6, Cumulative Reward: 28
Pull Number: 3, Arm Pulled: 11, Reward: 14, Cumulative Reward: 42
Pull Number: 4, Arm Pulled: 23, Reward: 15, Cumulative Reward: 57
Pull Number: 5, Arm Pulled: 23, Reward: 16, Cumulative Reward: 73
Pull Number: 6, Arm Pulled: 8, Reward: 9, Cumulative Reward: 82
Pull Number: 7, Arm Pulled: 23, Reward: 14, Cumulative Reward: 96
Pull Number: 8, Arm Pulled: 23, Reward: 10, Cumulative Reward: 106
Pull Number: 9, Arm Pulled: 23, Reward: 16, Cumulative Reward: 122
Pull Number: 10, Arm Pulled: 16, Reward: 13, Cumulative Reward: 135
Pull Number: 11, Arm Pulled: 18, Reward: 14, Cumulative Reward: 149
Pull Number: 12, Arm Pulled: 23, Reward: 13, Cumulative Reward: 162
Pull Number: 13, Arm Pulled: 23, Reward: 20, Cumulative Reward: 182
Pull Number: 14, Arm Pulled: 2, Reward: 26, Cumulative Reward: 208
Pull Number: 15, Arm Pulled: 14, Reward: 9, Cumulative Reward: 217
Pull Number: 16, Arm Pulled: 2, Reward: 25, Cumulative Reward: 242
Pull Number: 17, Arm Pulled: 2, Reward: 20, Cumulative Reward: 262
Pull Number: 18, Arm Pulled: 2, Reward: 22, Cumulative Reward: 284
Pull Number: 19, Arm Pulled: 2, Reward: 22, Cumulative Reward: 306
Pull Number: 20, Arm Pulled: 2, Reward: 19, Cumulative Reward: 325
Pull Number: 21, Arm Pulled: 2, Reward: 26, Cumulative Reward: 351
Pull Number: 22, Arm Pulled: 6, Reward: 19, Cumulative Reward: 370
Pull Number: 23, Arm Pulled: 2, Reward: 22, Cumulative Reward: 392
Pull Number: 24, Arm Pulled: 2, Reward: 21, Cumulative Reward: 413
Pull Number: 25, Arm Pulled: 2, Reward: 17, Cumulative Reward: 430
Pull Number: 26, Arm Pulled: 5, Reward: 23, Cumulative Reward: 453
Pull Number: 27, Arm Pulled: 5, Reward: 19, Cumulative Reward: 472
Pull Number: 28, Arm Pulled: 2, Reward: 18, Cumulative Reward: 490
Pull Number: 29, Arm Pulled: 8, Reward: 15, Cumulative Reward: 505
Pull Number: 30, Arm Pulled: 17, Reward: 13, Cumulative Reward: 518
Pull Number: 31, Arm Pulled: 2, Reward: 23, Cumulative Reward: 541
Pull Number: 32, Arm Pulled: 20, Reward: 23, Cumulative Reward: 564
Pull Number: 33, Arm Pulled: 2, Reward: 29, Cumulative Reward: 593
Pull Number: 34, Arm Pulled: 2, Reward: 20, Cumulative Reward: 613
Pull Number: 35, Arm Pulled: 20, Reward: 19, Cumulative Reward: 632
Pull Number: 36, Arm Pulled: 2, Reward: 27, Cumulative Reward: 659
Pull Number: 37, Arm Pulled: 2, Reward: 19, Cumulative Reward: 678
Pull Number: 38, Arm Pulled: 2, Reward: 17, Cumulative Reward: 695
Pull Number: 39, Arm Pulled: 18, Reward: 10, Cumulative Reward: 705
Pull Number: 40, Arm Pulled: 2, Reward: 19, Cumulative Reward: 724
Pull Number: 41, Arm Pulled: 2, Reward: 27, Cumulative Reward: 751
Pull Number: 42, Arm Pulled: 2, Reward: 20, Cumulative Reward: 771
Pull Number: 43, Arm Pulled: 22, Reward: 11, Cumulative Reward: 782
Pull Number: 44, Arm Pulled: 2, Reward: 26, Cumulative Reward: 808
Pull Number: 45, Arm Pulled: 5, Reward: 23, Cumulative Reward: 831
Pull Number: 46, Arm Pulled: 2, Reward: 31, Cumulative Reward: 862
Pull Number: 47, Arm Pulled: 2, Reward: 15, Cumulative Reward: 877
Pull Number: 48, Arm Pulled: 9, Reward: 16, Cumulative Reward: 893
Pull Number: 49, Arm Pulled: 2, Reward: 18, Cumulative Reward: 911
Pull Number: 50, Arm Pulled: 2, Reward: 21, Cumulative Reward: 932
Pull Number: 51, Arm Pulled: 8, Reward: 11, Cumulative Reward: 943
Pull Number: 52, Arm Pulled: 2, Reward: 30, Cumulative Reward: 973
Pull Number: 53, Arm Pulled: 2, Reward: 13, Cumulative Reward: 986
Pull Number: 54, Arm Pulled: 1, Reward: 16, Cumulative Reward: 1002
Pull Number: 55, Arm Pulled: 2, Reward: 24, Cumulative Reward: 1026
Pull Number: 56, Arm Pulled: 2, Reward: 20, Cumulative Reward: 1046
Pull Number: 57, Arm Pulled: 2, Reward: 27, Cumulative Reward: 1073
Pull Number: 58, Arm Pulled: 12, Reward: 5, Cumulative Reward: 1078
Pull Number: 59, Arm Pulled: 2, Reward: 29, Cumulative Reward: 1107
Pull Number: 60, Arm Pulled: 17, Reward: 13, Cumulative Reward: 1120
Pull Number: 61, Arm Pulled: 2, Reward: 16, Cumulative Reward: 1136
Pull Number: 62, Arm Pulled: 19, Reward: 9, Cumulative Reward: 1145
Pull Number: 63, Arm Pulled: 2, Reward: 21, Cumulative Reward: 1166
Pull Number: 64, Arm Pulled: 2, Reward: 23, Cumulative Reward: 1189
Pull Number: 65, Arm Pulled: 2, Reward: 24, Cumulative Reward: 1213
Pull Number: 66, Arm Pulled: 2, Reward: 19, Cumulative Reward: 1232
Pull Number: 67, Arm Pulled: 2, Reward: 15, Cumulative Reward: 1247
Pull Number: 68, Arm Pulled: 2, Reward: 18, Cumulative Reward: 1265
Pull Number: 69, Arm Pulled: 2, Reward: 22, Cumulative Reward: 1287
Pull Number: 70, Arm Pulled: 2, Reward: 14, Cumulative Reward: 1301
Pull Number: 71, Arm Pulled: 5, Reward: 22, Cumulative Reward: 1323
Pull Number: 72, Arm Pulled: 5, Reward: 13, Cumulative Reward: 1336
Pull Number: 73, Arm Pulled: 2, Reward: 19, Cumulative Reward: 1355
Pull Number: 74, Arm Pulled: 13, Reward: 23, Cumulative Reward: 1378
Pull Number: 75, Arm Pulled: 13, Reward: 11, Cumulative Reward: 1389
Pull Number: 76, Arm Pulled: 2, Reward: 24, Cumulative Reward: 1413
Pull Number: 77, Arm Pulled: 2, Reward: 21, Cumulative Reward: 1434
Pull Number: 78, Arm Pulled: 6, Reward: 12, Cumulative Reward: 1446
Pull Number: 79, Arm Pulled: 2, Reward: 25, Cumulative Reward: 1471
Pull Number: 80, Arm Pulled: 11, Reward: 5, Cumulative Reward: 1476
Pull Number: 81, Arm Pulled: 2, Reward: 18, Cumulative Reward: 1494
Pull Number: 82, Arm Pulled: 2, Reward: 25, Cumulative Reward: 1519
Pull Number: 83, Arm Pulled: 2, Reward: 26, Cumulative Reward: 1545
Pull Number: 84, Arm Pulled: 13, Reward: 26, Cumulative Reward: 1571
Pull Number: 85, Arm Pulled: 2, Reward: 19, Cumulative Reward: 1590
Pull Number: 86, Arm Pulled: 2, Reward: 28, Cumulative Reward: 1618
Pull Number: 87, Arm Pulled: 2, Reward: 22, Cumulative Reward: 1640
Pull Number: 88, Arm Pulled: 2, Reward: 25, Cumulative Reward: 1665
Pull Number: 89, Arm Pulled: 6, Reward: 15, Cumulative Reward: 1680
Pull Number: 90, Arm Pulled: 2, Reward: 22, Cumulative Reward: 1702
Pull Number: 91, Arm Pulled: 2, Reward: 22, Cumulative Reward: 1724
Pull Number: 92, Arm Pulled: 2, Reward: 24, Cumulative Reward: 1748
Pull Number: 93, Arm Pulled: 2, Reward: 20, Cumulative Reward: 1768
Pull Number: 94, Arm Pulled: 2, Reward: 21, Cumulative Reward: 1789
Pull Number: 95, Arm Pulled: 2, Reward: 23, Cumulative Reward: 1812
Pull Number: 96, Arm Pulled: 2, Reward: 20, Cumulative Reward: 1832
Pull Number: 97, Arm Pulled: 2, Reward: 23, Cumulative Reward: 1855
Pull Number: 98, Arm Pulled: 2, Reward: 23, Cumulative Reward: 1878
Pull Number: 99, Arm Pulled: 2, Reward: 24, Cumulative Reward: 1902
Pull Number: 100, Arm Pulled: 2, Reward: 15, Cumulative Reward: 1917

In [15]:
df = pd.DataFrame(result)
df

    Pull_Number  Arm_Pulled  Reward  Cumulative_Reward
0             1          23      22                 22
1             2          22       6                 28
2             3          11      14                 42
3             4          23      15                 57
4             5          23      16                 73
..          ...         ...     ...                ...
95           96           2      20               1832
96           97           2      23               1855
97           98           2      23               1878
98           99           2      24               1902
99          100           2      15               1917

[100 rows x 4 columns]

In [16]:
arm_rewards = {}
for pull_info in result:
    arm = pull_info['Arm_Pulled']
    reward = pull_info['Reward']
    if arm not in arm_rewards:
        arm_rewards[arm] = []
    arm_rewards[arm].append(reward)

In [19]:
avg_rewards = {arm: sum(rewards) / len(rewards) for arm, rewards in arm_rewards.items()}
best_arm = max(avg_rewards, key=avg_rewards.get)
best_arm_avg_reward = avg_rewards[best_arm]
print(f"Best Arm: {best_arm} with an average reward of {best_arm_avg_reward}")

Best Arm: 2 with an average reward of 21.838709677419356

In [20]:
df.to_csv('epsilon_greedy_results.csv', index=False)